version: '3.8'
services:
  db:
    image: mariadb:latest
    volumes:
      - container-volume:/var/lib/mysql
      - ./cms-database/database_content/current_database.sql:/docker-entrypoint-initdb.d/a1_schema.sql
      - ./cms-database/database_content/user_content.sql:/docker-entrypoint-initdb.d/a2_user.sql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=ferienwvk_db1
      - MYSQL_ROOT_PASSWORD=pass
  php:
    build: ./cms-frontend-api/.
    ports:
      - "80:80"
  backend:
    build: ./cms-backend/.
    ports:
      - "8001:8001"
    environment:
      - ROCKET_ENV=prod
      - ROCKET_PORT=8001
      - DATABASE_URL=mysql://root:pass@db:3306/ferienwvk_db1
  frontend:
     build: ./cms-frontend/.
     ports:
      - "8080:80" 
     environment:
      - BACKEND_API_URL=http://localhost:8001/
volumes:
  container-volume:
#networks:
#  intra-network:
